NumPy - Numerical Python

Advantages of Numpy Arrays:
  1. Allows several mathematical Operations
  2. Faster Operate

In [ ]:
import numpy as np

List vs Numpy - Time Taken

In [ ]:
from time import process_time

Time Taken by a List

In [ ]:
Lists = [i for i in range(10000)]

start = process_time()

Lists = [i+5 for i in Lists]

end = process_time()

print(end - start)

0.0010089440000000671


NumPy

In [ ]:
np_array = np.array([i for i in range(10000)])

start = process_time()

np_array += 5

end = process_time()

print(end - start)

0.00018774800000009861


List & NumPy Arrays

In [ ]:
#list
list1 = [1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [ ]:
#Numpy
np_array = np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

Creating a 1 dim array

In [ ]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [ ]:
a.shape

(4,)

Creating a 2 dim array

In [ ]:
b = np.array([(1,2,3,4),(5,6,7,8)])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
b.shape

(2, 4)

Float in Array

In [ ]:
c = np.array([(1,2,3,4),(5,6,7,8)],dtype=float)
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


Initial Placeholders iun NumPy arrays

In [ ]:
#create a numpy array of Zeros
x = np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
#create a numpy array of Ones
y = np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
#array of a particular value
z = np.full((5,4),10)
print(z)

[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


In [ ]:
#Create an identity matrix
p = np.eye(5)
print(p)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
#Random Float values in array
r = np.random.random((2,2))
print(r)

[[0.06248997 0.6147781 ]
 [0.3097775  0.85381911]]


In [ ]:
#random integer values array within a specific range
q = np.random.randint(10,100,(3,3))
print(q)

[[79 67 79]
 [86 60 13]
 [34 42 74]]


Analysing a Numpy Array

In [ ]:
# Array Dimension
q.shape

(3, 3)

In [ ]:
# Number of Dimension
q.ndim

2

In [ ]:
# Number of Elements In an Array
q.size

9

In [ ]:
#Checkting the Data tupe in Array
r.dtype

dtype('float64')

Mathematical Operations on np Array

In [ ]:
#lists
list1 = [1,2,3,4]
list2 = [5,6,7,8]

print(list1 + list2)      # marge

[1, 2, 3, 4, 5, 6, 7, 8]


In [ ]:
#Numpy
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))

print(a)
print(b)

[[2 1 4]
 [1 7 1]
 [1 6 9]]
[[17 19 18]
 [19 12 14]
 [14 14 17]]


In [ ]:
a+b

array([[19, 20, 22],
       [20, 19, 15],
       [15, 20, 26]])

In [ ]:
a-b

array([[-15, -18, -14],
       [-18,  -5, -13],
       [-13,  -8,  -8]])

In [ ]:
a*b

array([[ 34,  19,  72],
       [ 19,  84,  14],
       [ 14,  84, 153]])

In [ ]:
a/b

array([[0.11764706, 0.05263158, 0.22222222],
       [0.05263158, 0.58333333, 0.07142857],
       [0.07142857, 0.42857143, 0.52941176]])

Array Manipulation

In [ ]:
print(a)

[[2 1 4]
 [1 7 1]
 [1 6 9]]


In [ ]:
result  = np.transpose(a)
print(result)

[[2 1 1]
 [1 7 6]
 [4 1 9]]
